import re

with open('en.html', 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    'lang="es"': 'lang="en"',
    'Software de Alta Velocidad & Soluciones de Inteligencia Artificial': 'High-Speed Software & AI Solutions',
    'Desarrollo web de alto rendimiento, agentes de voz con IA y asistentes empresariales para escalar tu negocio.': 'High-performance web development, AI voice agents, and enterprise assistants to scale your business.',
    'Innovación IA': 'AI Innovation',
    'Servicios': 'Services',
    'Metodología': 'Methodology',
    'Contacto': 'Contact',
    '<span class="text-toh-turquoise">ES</span>': '<a href="index.html" class="text-toh-muted hover:text-white transition">ES</a>',
    '<a href="en.html" class="text-toh-muted hover:text-white transition">EN</a>': '<span class="text-toh-turquoise">EN</span>',
    'Contacto Directo': 'Direct Contact',
    'Inteligencia Artificial Aplicada a Negocios Reales': 'Artificial Intelligence Applied to Real Businesses',
    'Software de alta velocidad y': 'High-speed software and',
    'Agentes de IA que operan por ti': 'AI Agents that work for you',
    'Creamos presencia web con rendimiento 95+ e integramos telefonía con voz inteligente, recomendadores de menú y asistentes privados de documentos para PyMEs y corporativos.': 'We build web presence with 95+ performance and integrate smart voice telephony, menu recommenders, and private document assistants for SMBs and enterprises.',
    'Agendar Diagnóstico Gratuito': 'Schedule Free Diagnosis',
    'Atención Telefónica con IA': 'AI Telephone Support',
    'Lanzamiento de Landing Pages': 'Landing Page Launch',
    'Privacidad de Datos Corporativos': 'Corporate Data Privacy',
    'Soluciones Disruptivas': 'Disruptive Solutions',
    'Inteligencia Artificial de Impacto Inmediato': 'Immediate Impact Artificial Intelligence',
    'Automatizaciones diseñadas para resolver cuellos de botella específicos, no tecnología vacía.': 'Automations designed to solve specific bottlenecks, not empty tech.',
    'Para PyMEs con Alto Flujo': 'For High-Volume SMBs',
    'Recepcionista Virtual con Voz Inteligente': 'Virtual Receptionist with Smart Voice',
    'Número virtual o desvío configurado con voz natural mexicana que atiende llamadas cuando estás ocupado o fuera de horario. Resuelve dudas y toma reservas.': 'Virtual number or call forwarding with a natural voice that answers calls when you are busy or after hours. Resolves doubts and takes reservations.',
    'Voz fluida en español de México': 'Fluent, natural voice',
    'Envío del resumen a tu correo o CRM': 'Summary sent to your email or CRM',
    'Ideal para restaurantes, consultorios y talleres': 'Ideal for restaurants, clinics, and workshops',
    'Solicitar demostración en audio': 'Request audio demo',
    'Aumento de Ticket Promedio': 'Average Ticket Increase',
    'Mesero & Asistente Interactivo de Menú': 'Waiter & Interactive Menu Assistant',
    'Barra conversacional embebida en tu menú web. El cliente pide recomendaciones por presupuesto, antojo o restricción ("botana para 4 con $500") y arma su orden.': 'Conversational bar embedded in your web menu. Customers ask for recommendations by budget, cravings, or restrictions and build their order.',
    'Sugerencias cruzadas (cross-selling)': 'Cross-selling suggestions',
    'Exporta la comanda armada a tu sistema': 'Exports the built order to your system',
    'Para cafeterías, bares, restaurantes y boutiques': 'For cafes, bars, restaurants, and boutiques',
    'Ver cómo funciona en menú': 'See how it works in menu',
    'Corporativo & Confidencial': 'Corporate & Confidential',
    'Asistente Privado de Conocimiento (RAG)': 'Private Knowledge Assistant (RAG)',
    'Búsqueda semántica instantánea sobre manuales de operación, políticas de RRHH y contratos. Responde preguntas citando la cláusula y página exacta de origen.': 'Instant semantic search over operation manuals, HR policies, and contracts. Answers questions citing the exact clause and page source.',
    'Cifrado y sin exponer datos a terceros': 'Encrypted and without exposing data to third parties',
    'Acelera semanas de capacitación interna': 'Accelerates weeks of internal training',
    'Para colegios, maquilas, despachos y corporativos': 'For schools, factories, firms, and enterprises',
    'Consultar viabilidad técnica': 'Consult technical feasibility',
    'Líneas de Negocio': 'Business Lines',
    'Catálogo de Soluciones Toh Labs': 'Toh Labs Solutions Catalog',
    'Infraestructura digital moderna adaptada a cada etapa de madurez de tu empresa.': 'Modern digital infrastructure adapted to every maturity stage of your company.',
    '1. Presencia Digital de Alta Velocidad': '1. High-Speed Digital Presence',
    'Landing Pages One-Page (48-72h)': 'One-Page Landing Pages (48-72h)',
    'Rendimiento Google PageSpeed 95+, botón de contacto inmediato y SEO local configurado.': 'Google PageSpeed 95+ performance, immediate contact button, and local SEO configured.',
    'Sitios Corporativos Multi-página': 'Multi-page Corporate Sites',
    'Estructura modular para colegios, instituciones y firmas con descarga de folletos y formularios.': 'Modular structure for schools, institutions, and firms with brochure downloads and forms.',
    'Planes WaaS (Web as a Service)': 'WaaS Plans (Web as a Service)',
    'Hospedaje de alta disponibilidad, dominio propio, correos corporativos y mantenimiento mensual.': 'High-availability hosting, custom domain, corporate emails, and monthly maintenance.',
    '2. Catálogos & Soluciones Comerciales': '2. Catalogs & Commercial Solutions',
    'Menús Digitales QR Ultra-rápidos': 'Ultra-fast QR Digital Menus',
    'Apertura instantánea en celulares sin obligar a tus comensales a descargar archivos PDF pesados.': 'Instant opening on mobile without forcing your diners to download heavy PDF files.',
    'Catálogo E-commerce Ligero': 'Light E-commerce Catalog',
    'Fichas con botón de pedido directo a tu sistema o pasarela de pago para comercios locales.': 'Product cards with a direct order button to your system or payment gateway for local shops.',
    'Agente de Agendamiento en Calendario': 'Calendar Scheduling Agent',
    'Confirmación y sincronización de citas automáticamente con Google Calendar.': 'Automatic appointment confirmation and synchronization with Google Calendar.',
    '3. Inteligencia Artificial para PyMEs': '3. Artificial Intelligence for SMBs',
    'Telefonía con Voz Artificial': 'Telephony with Artificial Voice',
    'Responde llamadas con lenguaje natural y envía el lead en tiempo real a tu WhatsApp.': 'Answers calls with natural language and sends the lead in real-time to your CRM.',
    'Mesero Virtual Interactivo': 'Interactive Virtual Waiter',
    'Recomendador de platillos y paquetes según presupuesto y gustos del cliente en mesa.': 'Recommends dishes and packages based on customer budget and tastes at the table.',
    'Agentes Virtuales 24/7': '24/7 Virtual Agents',
    'Respuestas inmediatas a precios, horarios y catálogos sin dejar prospectos en visto.': 'Immediate responses to prices, schedules, and catalogs without leaving prospects on read.',
    '4. Soluciones B2B & Automatización': '4. B2B Solutions & Automation',
    'Asistente Privado RAG': 'Private RAG Assistant',
    'Centralización y búsqueda semántica en políticas, normativas y contratos sin alucinaciones.': 'Centralization and semantic search in policies, regulations, and contracts without hallucinations.',
    'Automatización de Flujos y CRM': 'Workflow Automation & CRM',
    'Conexión automática de formularios web con Google Sheets, sistemas internos y alertas de equipo.': 'Automatic connection of web forms with Google Sheets, internal systems, and team alerts.',
    'Auditoría y Arquitectura Segura': 'Security Audit & Architecture',
    'Pruebas de software exhaustivas (QA) para garantizar estabilidad antes de salir a producción.': 'Exhaustive software testing (QA) to ensure stability before going to production.',
    'Comienza Hoy': 'Start Today',
    'Hablemos de cómo modernizar tus procesos': 'Let\'s talk about modernizing your processes',
    'Ya sea que necesites una landing page lista en 72 horas o implementar un agente de voz con IA en tu negocio, te asesoramos de forma directa.': 'Whether you need a landing page ready in 72 hours or to implement an AI voice agent in your business, we advise you directly.',
    'Escríbenos a contacto@tohlabs.mx': 'Email us at contacto@tohlabs.mx',
    'Contactar por Correo': 'Contact by Email',
    'Mérida, Yucatán, México': 'Merida, Yucatan, Mexico',
    'Todos los derechos reservados.': 'All rights reserved.'
}

for k, v in replacements.items():
    html = html.replace(k, v)

with open('en.html', 'w', encoding='utf-8') as f:
    f.write(html)
